services:
  mproxy:
    image: ghcr.io/mikhail-angelov/mproxy:latest
    ports:
      - "8080:8080"   # plain HTTP
      - "8443:8443"   # HTTPS (TLS)
      - "1080:1080"   # SOCKS5
    env_file:
      - .env
    volumes:
      - ./certs:/certs:ro
      - ./blocked_ips.json:/app/blocked_ips.json:rw
    restart: unless-stopped
    labels:
      monic.enabled: "true"
      monic.name: "mproxy"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    stop_grace_period: 15s
